sequenceDiagram
    participant browser
    participant server

    Note right of browser: The browser sent form filled with information
    browser->>server: POST https://studies.cs.helsinki.fi/exampleapp/new_note
    activate server
    Note right of server: URL Redirect 302 Found
    server-->>browser: reload /example/notes
    deactivate server

    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/note.html
    activate server
    server-->>browser: the html
    deactivate server

    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/main.css
    activate server
    server-->>browser: the css file
    deactivate server

    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/main.js
    activate server
    server-->>browser: the JavaScript file
    deactivate server

